version: '3'
services:
  api:
    build: .
    command: sh -c "gunicorn --workers 3 wsgi:app --bind 0.0.0.0:5000"
    ports:
      - "5000:5000"

  nginx:
    image: nginx:1.17.4-alpine
    command: sh -c "rm -f /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - "1337:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api

